server:
  port: 8000

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 728487953692-lcrpcdi31so6r8c2ddp11r95hi1691vv.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
  mvc:
    static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: 1q2w3e4r

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB


mybatis:
  mapper-locations:
    - /mappers/*.xml

file:
  path: C:/web-3-202210/library/upload/
